### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by nliakm** [maierfelix/POGOserver#189] opened 2016-09-16 18:14 UTC
When i try to run the docker, following error appears:

chmod: cannot access '/POGOserver/run-linux.sh': No such file or directory
The command '/bin/sh -c chmod +x /POGOserver/run-linux.sh' returned a non-zero code: 1

so the run-linux-sh is missing in your repo? or do i have to add its somewhere else?

**Comment by DracoMilesX** [comment] 2016-09-16 18:19
Open the dockerfile with notepad++ or another proper text editor and remove line 39.

The file has been removed several commits ago but the dockerfile hasn't been changed yet because we where working on a better optimization for it.

**Comment by nliakm** [comment] 2016-09-16 21:09
Ok thank you. Did that.
But when the server is starting, it cant connect to mysql database. i dont know what ip adress i have to put in the cfg.js

172.0.0.1 not working
ip of the docker container also not working.

i dont have any clue what to do.

**Comment by Cronick** [comment] 2016-09-16 21:12
Have you setup an MySQL server with a database @nliakm

**Comment by DracoMilesX** [comment] 2016-09-16 21:32
@nliakm can you post a screenshot? How do you run the docker container?

Can you open a terminal and try ``service mysql start``? Which processes are running in the process tab (dunno if you got this? I do on my NAS ?

![image](https://cloud.githubusercontent.com/assets/13802602/18601846/b95a31b4-7c65-11e6-81c4-924ea57221c2.png)

Try looking in the Log as well

![image](https://cloud.githubusercontent.com/assets/13802602/18601859/ce3c2d58-7c65-11e6-8122-f5f8da2e7f78.png)

And verify if there are no exits or crashes.

**Comment by nliakm** [comment] 2016-09-16 22:57
I actually managed to make it work. the server is connected to the database but i cant connect my server via the ip.
what i have to do to let my container communicate with devices from outside?

**Comment by DracoMilesX** [comment] 2016-09-17 05:11
When you run the docker container you can map the ports. Check the mapped port for 3000. Docker by default has another ip range so it doesn't interfere with your home lan.

So you need to figure out the ip from your machine where docker is run on and then place it in the xposed module <host ip>:<mapped port> for outside(outside your wifi network) access you need to port forward the port and ip in your router

**Comment by nliakm** [comment] 2016-09-17 09:27
i hosted a few servers a few years ago. i know how to set it up in my router. never did it with docker. but for now, i just want to access from my computer (where docker is running).

Hm i thought i did it with the -p flag.
But i remember i once did a docker-tutorial, where i had to access the container from my browser . When im back home at sunday, i will check that.

**Comment by DracoMilesX** [comment] 2016-09-17 10:03
Yeah then you just need your laptop ip and the port you use in the run command unless you run it with gui.

**Comment by nliakm** [comment] 2016-09-17 11:06
Oh that was the problem. I took the wrong IP. Ok everything is working now!
Thanks for helping me out!

**Comment by Cronick** [comment] 2016-09-17 12:38
@DracoMilesX Alright about the MySQL thing. Have not played around with Docker, so it's why :D
But seems like the issue is fixed, so will close it :P

**Closed by Cronick** 2016-09-17 12:38 UTC
